# Generated by Django 5.0.3 on 2024-04-10 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_product_category'),
        ('api', '0002_product_category'),
    ]

    operations = [
    ]
